# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Anypoint CLI
      - name: Install Anypoint CLI
        run: npm install -g anypoint-cli-v4

        # Install Catalog CLI
      - name: Install Catalog CLI
        run: npm i api-catalog-cli -g

        # Install Catalog CLI
      - name: Automation using Anypoint CLI
        run: anypoint-cli-v4 account:user:describe --client_id 5061be79e0534c8cbc45bc343a60477f --client_secret B67a7A3c064c4f749A42a646FCd88c75
